spring.datasource.url=jdbc:mysql://ltnya0pnki2ck9w8.chr7pe7iynqr.eu-west-1.rds.amazonaws.com:3306/vz7kywb6b0wx1e6o
spring.datasource.username=mmfxnw798b1sc1wh
spring.datasource.password=s96t7qv1grvnl7vp
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
server.port=${PORT:8080}
